import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Main from "@/components/Main";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Football Destiny",
  description: "Generated by Burak & Alperen",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body>
      <Header />
      <Main>{children}</Main>
      </body>
      </html>
  );
}
